"""2020-12-6 delete field title

Revision ID: 073d78cb2ad0
Revises: 4cf7da88adf0
Create Date: 2020-12-06 13:26:48.556120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '073d78cb2ad0'
down_revision = '4cf7da88adf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('title', mysql.VARCHAR(length=128), nullable=True, comment='标题'))
    # ### end Alembic commands ###
