"""2020-12-5 crate_tables

Revision ID: 4cf7da88adf0
Revises: 
Create Date: 2020-12-05 13:55:58.736350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf7da88adf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False, comment='栏目名'),
    sa.Column('level', sa.SmallInteger(), nullable=True, comment='栏目等级'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='排序值'),
    sa.Column('module', sa.String(length=32), nullable=True, comment='所属模块'),
    sa.Column('upper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upper_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True, comment='标题'),
    sa.Column('icon', sa.String(length=128), nullable=True, comment='图标class'),
    sa.Column('color', sa.String(length=128), nullable=True, comment='图标颜色'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='链接地址'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='排序值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('focusing',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('focus_id', sa.Integer(), nullable=True, comment='聚焦内容id'),
    sa.Column('module', sa.String(length=128), nullable=True, comment='内容所属模块'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='排序值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navigation',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True, comment='导航标题'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='排序值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True, comment='标签名'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='排序值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=252), nullable=True, comment='文件名'),
    sa.Column('file_md5', sa.String(length=128), nullable=True, comment='文件md5'),
    sa.Column('file_type', sa.SmallInteger(), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('path', sa.String(length=256), nullable=True, comment='文件路径'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=32), nullable=False, comment='密码'),
    sa.Column('encryption', sa.String(length=6), nullable=False, comment='密文'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='昵称'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文章标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='文章内容'),
    sa.Column('comment', sa.Integer(), nullable=True, comment='评论人数'),
    sa.Column('view', sa.Integer(), nullable=True, comment='浏览次数'),
    sa.Column('recom', sa.Boolean(), nullable=True, comment='是否推荐，0否1是'),
    sa.Column('top', sa.Boolean(), nullable=True, comment='是否置顶'),
    sa.Column('published', sa.Boolean(), nullable=True, comment='是否发布0否1是'),
    sa.Column('publish_date', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='文章简要描述'),
    sa.Column('cover_id', sa.Integer(), nullable=True, comment='封面'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='栏目'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['cover_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True, comment='名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('version', sa.String(length=64), nullable=True, comment='版本'),
    sa.Column('frequency', sa.Integer(), nullable=True, comment='下载次数'),
    sa.Column('language', sa.String(length=128), nullable=True, comment='语言'),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='栏目'),
    sa.Column('cover_id', sa.Integer(), nullable=True, comment='封面'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['cover_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navigation_url',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True, comment='名称'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='跳转url'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='排序值'),
    sa.Column('navigation_id', sa.Integer(), nullable=True, comment='导航'),
    sa.ForeignKeyConstraint(['navigation_id'], ['navigation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture_album',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False, comment='图集名'),
    sa.Column('description', sa.Text(), nullable=True, comment='图集描述'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='栏目'),
    sa.Column('cover_id', sa.Integer(), nullable=True, comment='封面'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['cover_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True, comment='网站名'),
    sa.Column('slogan', sa.String(length=255), nullable=True, comment='标语'),
    sa.Column('notice', sa.String(length=255), nullable=True, comment='通知'),
    sa.Column('case_number', sa.String(length=255), nullable=True, comment='备案号'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='域名'),
    sa.Column('host', sa.String(length=255), nullable=True, comment='博客地址'),
    sa.Column('avatar_id', sa.Integer(), nullable=True, comment='头像'),
    sa.Column('logo_id', sa.Integer(), nullable=True, comment='logo的id'),
    sa.Column('background_id', sa.Integer(), nullable=True, comment='logo的id'),
    sa.ForeignKeyConstraint(['avatar_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['background_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['logo_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱，登录的账号'),
    sa.Column('password', sa.String(length=32), nullable=False, comment='密码'),
    sa.Column('encryption', sa.String(length=6), nullable=False, comment='密文'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='昵称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='简介'),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='0保密，1女，2男'),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_tag',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签id'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_table('comment',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='文章id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('theme_id', sa.Integer(), nullable=True, comment='主题id'),
    sa.Column('reply_comment_id', sa.Integer(), nullable=True, comment='回复的评论id'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['reply_comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picture',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('picture_album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['picture_album_id'], ['picture_album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    op.drop_table('comment')
    op.drop_table('article_tag')
    op.drop_table('user')
    op.drop_table('site')
    op.drop_table('picture_album')
    op.drop_table('navigation_url')
    op.drop_table('download')
    op.drop_table('article')
    op.drop_table('admin')
    op.drop_table('upload')
    op.drop_table('tag')
    op.drop_table('navigation')
    op.drop_table('focusing')
    op.drop_table('contact')
    op.drop_table('category')
    # ### end Alembic commands ###
